"""Constants for MeteoAM component."""
from homeassistant.components.weather import (
    ATTR_CONDITION_CLEAR_NIGHT,
    ATTR_CONDITION_CLOUDY,
    ATTR_CONDITION_FOG,
    ATTR_CONDITION_LIGHTNING_RAINY,
    ATTR_CONDITION_PARTLYCLOUDY,
    ATTR_CONDITION_POURING,
    ATTR_CONDITION_RAINY,
    ATTR_CONDITION_SNOWY,
    ATTR_CONDITION_SNOWY_RAINY,
    ATTR_CONDITION_SUNNY,
    ATTR_FORECAST_CLOUD_COVERAGE,
    ATTR_FORECAST_CONDITION,
    ATTR_FORECAST_HUMIDITY,
    ATTR_FORECAST_NATIVE_PRECIPITATION,
    ATTR_FORECAST_NATIVE_TEMP,
    ATTR_FORECAST_NATIVE_TEMP_LOW,
    ATTR_FORECAST_NATIVE_WIND_GUST_SPEED,
    ATTR_FORECAST_NATIVE_WIND_SPEED,
    ATTR_FORECAST_PRECIPITATION_PROBABILITY,
    ATTR_FORECAST_TIME,
    ATTR_FORECAST_WIND_BEARING,
    ATTR_WEATHER_CLOUD_COVERAGE,
    ATTR_WEATHER_DEW_POINT,
    ATTR_WEATHER_HUMIDITY,
    ATTR_WEATHER_PRESSURE,
    ATTR_WEATHER_TEMPERATURE,
    ATTR_WEATHER_VISIBILITY,
    ATTR_WEATHER_WIND_BEARING,
    ATTR_WEATHER_WIND_GUST_SPEED,
    ATTR_WEATHER_WIND_SPEED,
    DOMAIN as WEATHER_DOMAIN,
)

DOMAIN = "meteoam"

HOME_LOCATION_NAME = "Home"

CONF_TRACK_HOME = "track_home"

DEFAULT_HOME_LATITUDE = 52.3731339
DEFAULT_HOME_LONGITUDE = 4.8903147

ENTITY_ID_SENSOR_FORMAT_HOME = f"{WEATHER_DOMAIN}.meteoam_{HOME_LOCATION_NAME}"

CONDITIONS_MAP = {
    ATTR_CONDITION_SUNNY: {"01", "02"},
    ATTR_CONDITION_PARTLYCLOUDY: { "04", "34", "35"},
    ATTR_CONDITION_CLEAR_NIGHT: {"31"},
    ATTR_CONDITION_CLOUDY: {"05", "06", "07"},
    ATTR_CONDITION_FOG: {"03", "13", "14", "32"},
    ATTR_CONDITION_RAINY: {"08"},
    ATTR_CONDITION_POURING: {"09", "15"},
    ATTR_CONDITION_LIGHTNING_RAINY: {"10"},
    ATTR_CONDITION_SNOWY_RAINY: {"11", "12"},
    ATTR_CONDITION_SNOWY: {"16"},
    #"17"   #storm
    #"18"   
    #"19"   #sand storm
}

FORECAST_MAP = {
    ATTR_FORECAST_CONDITION: "icon",
    ATTR_FORECAST_NATIVE_PRECIPITATION: "precipitation",
    ATTR_FORECAST_PRECIPITATION_PROBABILITY: "precipitation_probability",
    ATTR_FORECAST_NATIVE_TEMP: "2t",
    ATTR_FORECAST_NATIVE_TEMP_LOW: "2t_min",
    ATTR_FORECAST_TIME: "localDateTime",
    ATTR_FORECAST_WIND_BEARING: "wdir",
    ATTR_FORECAST_NATIVE_WIND_SPEED: "wkmh",
    ATTR_FORECAST_NATIVE_WIND_GUST_SPEED: "wspd",
    ATTR_FORECAST_CLOUD_COVERAGE: "cloudiness",
    ATTR_FORECAST_HUMIDITY: "r",
}

ATTR_MAP = {
    ATTR_WEATHER_HUMIDITY: "r",
    ATTR_WEATHER_PRESSURE: "pmsl",
    ATTR_WEATHER_TEMPERATURE: "2t",
    ATTR_WEATHER_VISIBILITY: "visibility",
    ATTR_WEATHER_WIND_BEARING: "wdir",
    ATTR_WEATHER_WIND_SPEED: "wkmh",
    ATTR_WEATHER_WIND_GUST_SPEED: "wspd",
    ATTR_WEATHER_CLOUD_COVERAGE: "cloudiness",
    ATTR_WEATHER_DEW_POINT: "dew_point",
}
